version: '3.8'

services:
  face_detect:
    restart: always
    build: ./face_detect
    environment:
      - FLASK_ENV=docker
    command: bash -c "python3 main.py"
    ports:
      - 8080:8000
    networks:
      - default

