version: '3.8'

services:
  face_detect:
    restart: always
    build: .
    environment:
      - FLASK_ENV=docker
    command: bash -c "python3 -c main.py"
    ports:
      - 5000:5000
    networks:
      - default

